services:
  - type: web
    name: your-app-name
    env: docker
    region: oregon  # or choose another region
    plan: free  # or choose paid plan as needed
    branch: main  # or your deployment branch
    dockerCommand: streamlit run app.py --server.address 0.0.0.0
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /_stcore/health
    numInstances: 1